### ISSUE TITLE
Add config file for options

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/birdcage#4]
It seems like one fairly easy way to make the pipeline much more user-friendly is to centralize the options in a config file and have each file read it as necessary. 

Some of the configs to start with:

- MongoDB info
- RabbitMQ info
- CoreNLP SQLite DB location
- output Mongo collecition

**Comment by solaimani** [comment]
Added in commit 0e2b928 and 794bcd8

**Comment by solaimani** [comment]
Output of MongoDB will be under Articles (DB) and Article (Collection)
